 /***************************************************************************//**
 *   @file   talise_tinyiiod.h
 *   @brief  Header file of AD9361 Driver.
********************************************************************************
 * Copyright 2019(c) Analog Devices, Inc.
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *  - Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  - Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  - Neither the name of Analog Devices, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *  - The use of this software may or may not infringe the patent rights
 *    of one or more patent holders.  This license does not release you
 *    from the requirement that you obtain separate licenses from these
 *    patent holders to use this software.
 *  - Use of the software either in source or binary form, must be run
 *    on or directly connected to an Analog Devices Inc. component.
 *
 * THIS SOFTWARE IS PROVIDED BY ANALOG DEVICES "AS IS\" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, NON-INFRINGEMENT,
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL ANALOG DEVICES BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, INTELLECTUAL PROPERTY RIGHTS, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*******************************************************************************/

#ifndef TALISE_TINYIIOD_H
#define TALISE_TINYIIOD_H

#include <stdint.h>
#include "tinyiiod.h"
#include "axi_adc_core.h"
#include "axi_dmac.h"

static const char * const  xml =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<!DOCTYPE context ["
"<!ELEMENT context (device | context-attribute)*>"
"<!ELEMENT context-attribute EMPTY>"
"<!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*>"
"<!ELEMENT channel (scan-element? , attribute*)>"
"<!ELEMENT attribute EMPTY>"
"<!ELEMENT scan-element EMPTY>"
"<!ELEMENT debug-attribute EMPTY>"
"<!ELEMENT buffer-attribute EMPTY>"
"<!ATTLIST context name CDATA #REQUIRED>"
"<!ATTLIST context description CDATA #IMPLIED>"
"<!ATTLIST context-attribute name CDATA #REQUIRED>"
"<!ATTLIST context-attribute value CDATA #REQUIRED>"
"<!ATTLIST device id CDATA #REQUIRED>"
"<!ATTLIST device name CDATA #IMPLIED>"
"<!ATTLIST channel id CDATA #REQUIRED>"
"<!ATTLIST channel type (input | output) #REQUIRED>"
"<!ATTLIST channel name CDATA #IMPLIED>"
"<!ATTLIST scan-element index CDATA #REQUIRED>"
"<!ATTLIST scan-element format CDATA #REQUIRED>"
"<!ATTLIST scan-element scale CDATA #IMPLIED>"
"<!ATTLIST attribute name CDATA #REQUIRED>"
"<!ATTLIST attribute filename CDATA #IMPLIED>"
"<!ATTLIST debug-attribute name CDATA #REQUIRED>"
"<!ATTLIST buffer-attribute name CDATA #REQUIRED>"
"]>"
"<context name=\"xml\" description=\"Linux analog 4.14.0-gd90f527 #120 SMP PREEMPT Wed Sep 11 12:28:24 IST 2019 armv7l\">"
  "<context-attribute name=\"local,kernel\" value=\"4.14.0-gd90f527\"/>"
  "<device id=\"ad7291\" name=\"ad7291\">"
    "<channel id=\"voltage6\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage6_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"temp0\" type=\"input\">"
      "<attribute name=\"mean_raw\" filename=\"in_temp0_mean_raw\"/>"
      "<attribute name=\"raw\" filename=\"in_temp0_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_temp0_scale\"/>"
    "</channel>"
    "<channel id=\"voltage3\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage3_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"voltage7\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage7_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"voltage0\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage0_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"voltage4\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage4_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"voltage1\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage1_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"voltage5\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage5_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
    "<channel id=\"voltage2\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage2_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage_scale\"/>"
    "</channel>"
  "</device>"
  "<device id=\"xadc\" name=\"xadc\">"
    "<channel id=\"voltage5\" name=\"vccoddr\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage5_vccoddr_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage5_vccoddr_scale\"/>"
    "</channel>"
    "<channel id=\"voltage0\" name=\"vccint\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage0_vccint_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage0_vccint_scale\"/>"
    "</channel>"
    "<channel id=\"voltage4\" name=\"vccpaux\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage4_vccpaux_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage4_vccpaux_scale\"/>"
    "</channel>"
    "<channel id=\"temp0\" type=\"input\">"
      "<attribute name=\"offset\" filename=\"in_temp0_offset\"/>"
      "<attribute name=\"raw\" filename=\"in_temp0_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_temp0_scale\"/>"
    "</channel>"
    "<channel id=\"voltage7\" name=\"vrefn\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage7_vrefn_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage7_vrefn_scale\"/>"
    "</channel>"
    "<channel id=\"voltage1\" name=\"vccaux\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage1_vccaux_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage1_vccaux_scale\"/>"
    "</channel>"
    "<channel id=\"voltage2\" name=\"vccbram\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage2_vccbram_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage2_vccbram_scale\"/>"
    "</channel>"
    "<channel id=\"voltage3\" name=\"vccpint\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage3_vccpint_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage3_vccpint_scale\"/>"
    "</channel>"
    "<channel id=\"voltage6\" name=\"vrefp\" type=\"input\">"
      "<attribute name=\"raw\" filename=\"in_voltage6_vrefp_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage6_vrefp_scale\"/>"
    "</channel>"
    "<attribute name=\"sampling_frequency\"/>"
  "</device>"
  "<device id=\"ad9528-1\" name=\"ad9528-1\">"
    "<channel id=\"altvoltage12\" name=\"DEV_SYSREF\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage12_DEV_SYSREF_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage12_DEV_SYSREF_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage12_DEV_SYSREF_raw\"/>"
    "</channel>"
    "<channel id=\"altvoltage1\" name=\"FMC_CLK\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage1_FMC_CLK_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage1_FMC_CLK_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage1_FMC_CLK_raw\"/>"
    "</channel>"
    "<channel id=\"altvoltage13\" name=\"DEV_CLK\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage13_DEV_CLK_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage13_DEV_CLK_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage13_DEV_CLK_raw\"/>"
    "</channel>"
    "<channel id=\"altvoltage3\" name=\"FMC_SYSREF\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage3_FMC_SYSREF_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage3_FMC_SYSREF_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage3_FMC_SYSREF_raw\"/>"
    "</channel>"
    "<attribute name=\"pll1_feedback_clk_present\"/>"
    "<attribute name=\"pll1_locked\"/>"
    "<attribute name=\"pll1_reference_clk_a_present\"/>"
    "<attribute name=\"pll1_reference_clk_ab_missing\"/>"
    "<attribute name=\"pll1_reference_clk_b_present\"/>"
    "<attribute name=\"pll2_feedback_clk_present\"/>"
    "<attribute name=\"pll2_locked\"/>"
    "<attribute name=\"sync_dividers\"/>"
    "<attribute name=\"vcxo_clk_present\"/>"
    "<debug-attribute name=\"direct_reg_access\"/>"
  "</device>"
  "<device id=\"adrv9009-phy\" name=\"adrv9009-phy\">"
    "<channel id=\"voltage1\" type=\"input\">"
      "<attribute name=\"gain_control_mode\" filename=\"in_voltage1_gain_control_mode\"/>"
      "<attribute name=\"gain_control_mode_available\" filename=\"in_voltage1_gain_control_mode_available\"/>"
      "<attribute name=\"gain_control_pin_mode_en\" filename=\"in_voltage1_gain_control_pin_mode_en\"/>"
      "<attribute name=\"hardwaregain\" filename=\"in_voltage1_hardwaregain\"/>"
      "<attribute name=\"hd2_tracking_en\" filename=\"in_voltage1_hd2_tracking_en\"/>"
      "<attribute name=\"powerdown\" filename=\"in_voltage1_powerdown\"/>"
      "<attribute name=\"quadrature_tracking_en\" filename=\"in_voltage1_quadrature_tracking_en\"/>"
      "<attribute name=\"rf_bandwidth\" filename=\"in_voltage1_rf_bandwidth\"/>"
      "<attribute name=\"rssi\" filename=\"in_voltage1_rssi\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage1_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage3\" type=\"input\">"
      "<attribute name=\"hardwaregain\" filename=\"in_voltage3_hardwaregain\"/>"
      "<attribute name=\"powerdown\" filename=\"in_voltage3_powerdown\"/>"
      "<attribute name=\"quadrature_tracking_en\" filename=\"in_voltage3_quadrature_tracking_en\"/>"
      "<attribute name=\"rf_bandwidth\" filename=\"in_voltage3_rf_bandwidth\"/>"
      "<attribute name=\"rf_port_select\" filename=\"in_voltage3_rf_port_select\"/>"
      "<attribute name=\"rf_port_select_available\" filename=\"in_voltage3_rf_port_select_available\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage3_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage1\" type=\"output\">"
      "<attribute name=\"atten_control_pin_mode_en\" filename=\"out_voltage1_atten_control_pin_mode_en\"/>"
      "<attribute name=\"hardwaregain\" filename=\"out_voltage1_hardwaregain\"/>"
      "<attribute name=\"lo_leakage_tracking_en\" filename=\"out_voltage1_lo_leakage_tracking_en\"/>"
      "<attribute name=\"pa_protection_en\" filename=\"out_voltage1_pa_protection_en\"/>"
      "<attribute name=\"powerdown\" filename=\"out_voltage1_powerdown\"/>"
      "<attribute name=\"quadrature_tracking_en\" filename=\"out_voltage1_quadrature_tracking_en\"/>"
      "<attribute name=\"rf_bandwidth\" filename=\"out_voltage1_rf_bandwidth\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage6\" type=\"input\">"
      "<attribute name=\"offset\" filename=\"in_voltage6_offset\"/>"
      "<attribute name=\"raw\" filename=\"in_voltage6_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage6_scale\"/>"
    "</channel>"
    "<channel id=\"voltage8\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage8_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage8_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage8_scale\"/>"
    "</channel>"
    "<channel id=\"voltage5\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage5_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage5_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage5_scale\"/>"
    "</channel>"
    "<channel id=\"voltage0\" type=\"input\">"
      "<attribute name=\"gain_control_mode\" filename=\"in_voltage0_gain_control_mode\"/>"
      "<attribute name=\"gain_control_mode_available\" filename=\"in_voltage0_gain_control_mode_available\"/>"
      "<attribute name=\"gain_control_pin_mode_en\" filename=\"in_voltage0_gain_control_pin_mode_en\"/>"
      "<attribute name=\"hardwaregain\" filename=\"in_voltage0_hardwaregain\"/>"
      "<attribute name=\"hd2_tracking_en\" filename=\"in_voltage0_hd2_tracking_en\"/>"
      "<attribute name=\"powerdown\" filename=\"in_voltage0_powerdown\"/>"
      "<attribute name=\"quadrature_tracking_en\" filename=\"in_voltage0_quadrature_tracking_en\"/>"
      "<attribute name=\"rf_bandwidth\" filename=\"in_voltage0_rf_bandwidth\"/>"
      "<attribute name=\"rssi\" filename=\"in_voltage0_rssi\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage0_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage2\" type=\"input\">"
      "<attribute name=\"hardwaregain\" filename=\"in_voltage2_hardwaregain\"/>"
      "<attribute name=\"powerdown\" filename=\"in_voltage2_powerdown\"/>"
      "<attribute name=\"quadrature_tracking_en\" filename=\"in_voltage2_quadrature_tracking_en\"/>"
      "<attribute name=\"rf_bandwidth\" filename=\"in_voltage2_rf_bandwidth\"/>"
      "<attribute name=\"rf_port_select\" filename=\"in_voltage2_rf_port_select\"/>"
      "<attribute name=\"rf_port_select_available\" filename=\"in_voltage2_rf_port_select_available\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage2_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage9\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage9_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage9_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage9_scale\"/>"
    "</channel>"
    "<channel id=\"voltage4\" type=\"input\">"
      "<attribute name=\"offset\" filename=\"in_voltage4_offset\"/>"
      "<attribute name=\"raw\" filename=\"in_voltage4_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage4_scale\"/>"
    "</channel>"
    "<channel id=\"voltage12\" type=\"output\">"
      "<attribute name=\"raw\" filename=\"out_voltage12_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage12_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage0\" name=\"TRX_LO\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage0_TRX_LO_frequency\"/>"
      "<attribute name=\"frequency_hopping_mode\" filename=\"out_altvoltage0_TRX_LO_frequency_hopping_mode\"/>"
      "<attribute name=\"frequency_hopping_mode_enable\" filename=\"out_altvoltage0_TRX_LO_frequency_hopping_mode_enable\"/>"
    "</channel>"
    "<channel id=\"voltage4\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage4_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage4_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage4_scale\"/>"
    "</channel>"
    "<channel id=\"voltage10\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage10_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage10_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage10_scale\"/>"
    "</channel>"
    "<channel id=\"voltage13\" type=\"output\">"
      "<attribute name=\"raw\" filename=\"out_voltage13_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage13_scale\"/>"
    "</channel>"
    "<channel id=\"voltage3\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage3_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage3_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage3_scale\"/>"
    "</channel>"
    "<channel id=\"voltage7\" type=\"input\">"
      "<attribute name=\"offset\" filename=\"in_voltage7_offset\"/>"
      "<attribute name=\"raw\" filename=\"in_voltage7_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage7_scale\"/>"
    "</channel>"
    "<channel id=\"voltage2\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage2_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage2_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage2_scale\"/>"
    "</channel>"
    "<channel id=\"voltage6\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage6_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage6_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage6_scale\"/>"
    "</channel>"
    "<channel id=\"temp0\" type=\"input\">"
      "<attribute name=\"input\" filename=\"in_temp0_input\"/>"
    "</channel>"
    "<channel id=\"voltage0\" type=\"output\">"
      "<attribute name=\"atten_control_pin_mode_en\" filename=\"out_voltage0_atten_control_pin_mode_en\"/>"
      "<attribute name=\"hardwaregain\" filename=\"out_voltage0_hardwaregain\"/>"
      "<attribute name=\"lo_leakage_tracking_en\" filename=\"out_voltage0_lo_leakage_tracking_en\"/>"
      "<attribute name=\"pa_protection_en\" filename=\"out_voltage0_pa_protection_en\"/>"
      "<attribute name=\"powerdown\" filename=\"out_voltage0_powerdown\"/>"
      "<attribute name=\"quadrature_tracking_en\" filename=\"out_voltage0_quadrature_tracking_en\"/>"
      "<attribute name=\"rf_bandwidth\" filename=\"out_voltage0_rf_bandwidth\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"altvoltage1\" type=\"output\">"
      "<attribute name=\"AUX_OBS_RX_LO_frequency\" filename=\"out_altvoltage1_AUX_OBS_RX_LO_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage11\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage11_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage11_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage11_scale\"/>"
    "</channel>"
    "<channel id=\"voltage7\" type=\"output\">"
      "<attribute name=\"offset\" filename=\"out_voltage7_offset\"/>"
      "<attribute name=\"raw\" filename=\"out_voltage7_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_voltage7_scale\"/>"
    "</channel>"
    "<channel id=\"voltage5\" type=\"input\">"
      "<attribute name=\"offset\" filename=\"in_voltage5_offset\"/>"
      "<attribute name=\"raw\" filename=\"in_voltage5_raw\"/>"
      "<attribute name=\"scale\" filename=\"in_voltage5_scale\"/>"
    "</channel>"
    "<attribute name=\"calibrate\"/>"
    "<attribute name=\"calibrate_frm_en\"/>"
    "<attribute name=\"calibrate_rx_phase_correction_en\"/>"
    "<attribute name=\"calibrate_rx_qec_en\"/>"
    "<attribute name=\"calibrate_tx_lol_en\"/>"
    "<attribute name=\"calibrate_tx_lol_ext_en\"/>"
    "<attribute name=\"calibrate_tx_qec_en\"/>"
    "<attribute name=\"ensm_mode\"/>"
    "<attribute name=\"ensm_mode_available\"/>"
    "<attribute name=\"gain_table_config\"/>"
    "<attribute name=\"multichip_sync\"/>"
    "<attribute name=\"profile_config\"/>"
    "<debug-attribute name=\"bist_tone\"/>"
    "<debug-attribute name=\"bist_framer_b_loopback\"/>"
    "<debug-attribute name=\"bist_framer_a_loopback\"/>"
    "<debug-attribute name=\"bist_framer_b_prbs\"/>"
    "<debug-attribute name=\"bist_framer_a_prbs\"/>"
    "<debug-attribute name=\"initialize\"/>"
    "<debug-attribute name=\"adi,aux-pll-lo-frequency_hz\"/>"
    "<debug-attribute name=\"adi,trx-pll-lo-frequency_hz\"/>"
    "<debug-attribute name=\"adi,dig-clocks-rf-pll-phase-sync-mode\"/>"
    "<debug-attribute name=\"adi,dig-clocks-rf-pll-use-external-lo\"/>"
    "<debug-attribute name=\"adi,dig-clocks-clk-pll-hs-div\"/>"
    "<debug-attribute name=\"adi,dig-clocks-clk-pll-vco-freq_khz\"/>"
    "<debug-attribute name=\"adi,dig-clocks-device-clock_khz\"/>"
    "<debug-attribute name=\"adi,tx-settings-dis-tx-data-if-pll-unlock\"/>"
    "<debug-attribute name=\"adi,tx-settings-tx2-atten_md-b\"/>"
    "<debug-attribute name=\"adi,tx-settings-tx1-atten_md-b\"/>"
    "<debug-attribute name=\"adi,tx-settings-tx-atten-step-size\"/>"
    "<debug-attribute name=\"adi,tx-settings-tx-channels\"/>"
    "<debug-attribute name=\"adi,tx-settings-deframer-sel\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-bbf3d-bcorner_khz\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-dac3d-bcorner_khz\"/>"
    "<debug-attribute name=\"adi,tx-profile-rf-bandwidth_hz\"/>"
    "<debug-attribute name=\"adi,tx-profile-primary-sig-bandwidth_hz\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-input-rate_khz\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-int5-interpolation\"/>"
    "<debug-attribute name=\"adi,tx-profile-thb3-interpolation\"/>"
    "<debug-attribute name=\"adi,tx-profile-thb2-interpolation\"/>"
    "<debug-attribute name=\"adi,tx-profile-thb1-interpolation\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-fir-interpolation\"/>"
    "<debug-attribute name=\"adi,tx-profile-dac-div\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-fir-num-fir-coefs\"/>"
    "<debug-attribute name=\"adi,tx-profile-tx-fir-gain_db\"/>"
    "<debug-attribute name=\"adi,obs-settings-obs-rx-lo-source\"/>"
    "<debug-attribute name=\"adi,obs-settings-obs-rx-channels-enable\"/>"
    "<debug-attribute name=\"adi,obs-settings-framer-sel\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-orx2-min-gain-index\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-orx2-max-gain-index\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-orx1-min-gain-index\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-orx1-max-gain-index\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-orx2-gain-index\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-orx1-gain-index\"/>"
    "<debug-attribute name=\"adi,orx-gain-control-gain-mode\"/>"
    "<debug-attribute name=\"adi,orx-profile-orx-ddc-mode\"/>"
    "<debug-attribute name=\"adi,orx-profile-rx-bbf3d-bcorner_khz\"/>"
    "<debug-attribute name=\"adi,orx-profile-rf-bandwidth_hz\"/>"
    "<debug-attribute name=\"adi,orx-profile-orx-output-rate_khz\"/>"
    "<debug-attribute name=\"adi,orx-profile-rhb1-decimation\"/>"
    "<debug-attribute name=\"adi,orx-profile-rx-dec5-decimation\"/>"
    "<debug-attribute name=\"adi,orx-profile-rx-fir-decimation\"/>"
    "<debug-attribute name=\"adi,orx-profile-rx-fir-num-fir-coefs\"/>"
    "<debug-attribute name=\"adi,orx-profile-rx-fir-gain_db\"/>"
    "<debug-attribute name=\"adi,rx-settings-rx-channels\"/>"
    "<debug-attribute name=\"adi,rx-settings-framer-sel\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-rx2-min-gain-index\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-rx2-max-gain-index\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-rx1-min-gain-index\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-rx1-max-gain-index\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-rx2-gain-index\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-rx1-gain-index\"/>"
    "<debug-attribute name=\"adi,rx-gain-control-gain-mode\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-bnco2-freq_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-bnco1-freq_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-binput-center-freq_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-binput-band-width_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-a-nco2-freq_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-a-nco1-freq_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-a-input-center-freq_khz\"/>"
    "<debug-attribute name=\"adi,rx-nco-shifter-band-a-input-band-width_khz\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-ddc-mode\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-bbf3d-bcorner_khz\"/>"
    "<debug-attribute name=\"adi,rx-profile-rf-bandwidth_hz\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-output-rate_khz\"/>"
    "<debug-attribute name=\"adi,rx-profile-rhb1-decimation\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-dec5-decimation\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-fir-decimation\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-fir-num-fir-coefs\"/>"
    "<debug-attribute name=\"adi,rx-profile-rx-fir-gain_db\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-tx2-peak-threshold\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-tx1-peak-threshold\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-peak-count\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-tx2-power-threshold\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-tx1-power-threshold\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-tx-atten-step\"/>"
    "<debug-attribute name=\"adi,tx-pa-protection-avg-duration\"/>"
    "<debug-attribute name=\"adi,tx2-atten-ctrl-pin-enable\"/>"
    "<debug-attribute name=\"adi,tx2-atten-ctrl-pin-tx-atten-dec-pin\"/>"
    "<debug-attribute name=\"adi,tx2-atten-ctrl-pin-tx-atten-inc-pin\"/>"
    "<debug-attribute name=\"adi,tx2-atten-ctrl-pin-step-size\"/>"
    "<debug-attribute name=\"adi,tx1-atten-ctrl-pin-enable\"/>"
    "<debug-attribute name=\"adi,tx1-atten-ctrl-pin-tx-atten-dec-pin\"/>"
    "<debug-attribute name=\"adi,tx1-atten-ctrl-pin-tx-atten-inc-pin\"/>"
    "<debug-attribute name=\"adi,tx1-atten-ctrl-pin-step-size\"/>"
    "<debug-attribute name=\"adi,rx2-gain-ctrl-pin-enable\"/>"
    "<debug-attribute name=\"adi,rx2-gain-ctrl-pin-rx-gain-dec-pin\"/>"
    "<debug-attribute name=\"adi,rx2-gain-ctrl-pin-rx-gain-inc-pin\"/>"
    "<debug-attribute name=\"adi,rx2-gain-ctrl-pin-dec-step\"/>"
    "<debug-attribute name=\"adi,rx2-gain-ctrl-pin-inc-step\"/>"
    "<debug-attribute name=\"adi,rx1-gain-ctrl-pin-enable\"/>"
    "<debug-attribute name=\"adi,rx1-gain-ctrl-pin-rx-gain-dec-pin\"/>"
    "<debug-attribute name=\"adi,rx1-gain-ctrl-pin-rx-gain-inc-pin\"/>"
    "<debug-attribute name=\"adi,rx1-gain-ctrl-pin-dec-step\"/>"
    "<debug-attribute name=\"adi,rx1-gain-ctrl-pin-inc-step\"/>"
    "<debug-attribute name=\"adi,fhm-mode-fhm-init-frequency_hz\"/>"
    "<debug-attribute name=\"adi,fhm-mode-fhm-exit-mode\"/>"
    "<debug-attribute name=\"adi,fhm-mode-fhm-trigger-mode\"/>"
    "<debug-attribute name=\"adi,fhm-mode-enable-mcs-sync\"/>"
    "<debug-attribute name=\"adi,fhm-mode-fhm-enable\"/>"
    "<debug-attribute name=\"adi,fhm-config-fhm-max-freq_mhz\"/>"
    "<debug-attribute name=\"adi,fhm-config-fhm-min-freq_mhz\"/>"
    "<debug-attribute name=\"adi,fhm-config-fhm-gpio-pin\"/>"
    "<debug-attribute name=\"adi,orx-lo-cfg-gpio-select\"/>"
    "<debug-attribute name=\"adi,orx-lo-cfg-disable-aux-pll-relocking\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-en-tx-tracking-cals-enable\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-en-tx-tracking-cals-polarity\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-en-tx-tracking-cals-gpio-pin-sel\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx2-tx-sel1-pin-enable\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx2-tx-sel1-pin-polarity\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx2-tx-sel1-pin-gpio-pin-sel\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx2-tx-sel0-pin-enable\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx2-tx-sel0-pin-polarity\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx2-tx-sel0-pin-gpio-pin-sel\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx1-tx-sel1-pin-enable\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx1-tx-sel1-pin-polarity\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx1-tx-sel1-pin-gpio-pin-sel\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx1-tx-sel0-pin-enable\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx1-tx-sel0-pin-polarity\"/>"
    "<debug-attribute name=\"adi,arm-gpio-config-orx1-tx-sel0-pin-gpio-pin-sel\"/>"
    "<debug-attribute name=\"adi,jesd204-sysref-lvds-pn-invert\"/>"
    "<debug-attribute name=\"adi,jesd204-sysref-lvds-mode\"/>"
    "<debug-attribute name=\"adi,jesd204-des-eq-setting\"/>"
    "<debug-attribute name=\"adi,jesd204-des-invert-lane-polarity\"/>"
    "<debug-attribute name=\"adi,jesd204-ser-invert-lane-polarity\"/>"
    "<debug-attribute name=\"adi,jesd204-ser-pre-emphasis\"/>"
    "<debug-attribute name=\"adi,jesd204-ser-amplitude\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-enable-manual-lane-xbar\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-syncb-out-cmos-drive-level\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-syncb-out-cmos-slew-rate\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-syncb-out-lvds-pn-invert\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-syncb-out-lvds-mode\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-np\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-syncb-out-select\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-new-sysref-on-relink\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-lmfc-offset\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-deserializer-lane-crossbar\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-deserializer-lanes-enabled\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-external-sysref\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-scramble\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-k\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-m\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-lane0-id\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-device-id\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-b-bank-id\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-enable-manual-lane-xbar\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-syncb-out-cmos-drive-level\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-syncb-out-cmos-slew-rate\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-syncb-out-lvds-pn-invert\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-syncb-out-lvds-mode\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-np\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-syncb-out-select\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-new-sysref-on-relink\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-lmfc-offset\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-deserializer-lane-crossbar\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-deserializer-lanes-enabled\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-external-sysref\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-scramble\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-k\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-m\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-lane0-id\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-device-id\"/>"
    "<debug-attribute name=\"adi,jesd204-deframer-a-bank-id\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-enable-manual-lane-xbar\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-syncb-in-lvds-pn-invert\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-syncb-in-lvds-mode\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-over-sample\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-syncb-in-select\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-new-sysref-on-relink\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-lmfc-offset\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-serializer-lane-crossbar\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-serializer-lanes-enabled\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-external-sysref\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-scramble\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-np\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-f\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-k\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-m\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-lane0-id\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-device-id\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-b-bank-id\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-enable-manual-lane-xbar\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-syncb-in-lvds-pn-invert\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-syncb-in-lvds-mode\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-over-sample\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-syncb-in-select\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-new-sysref-on-relink\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-lmfc-offset\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-serializer-lane-crossbar\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-serializer-lanes-enabled\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-external-sysref\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-scramble\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-np\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-f\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-k\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-m\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-lane0-id\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-device-id\"/>"
    "<debug-attribute name=\"adi,jesd204-framer-a-bank-id\"/>"
    "<debug-attribute name=\"adi,aux-dac-values11\"/>"
    "<debug-attribute name=\"adi,aux-dac-values10\"/>"
    "<debug-attribute name=\"adi,aux-dac-values9\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution9\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref9\"/>"
    "<debug-attribute name=\"adi,aux-dac-values8\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution8\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref8\"/>"
    "<debug-attribute name=\"adi,aux-dac-values7\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution7\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref7\"/>"
    "<debug-attribute name=\"adi,aux-dac-values6\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution6\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref6\"/>"
    "<debug-attribute name=\"adi,aux-dac-values5\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution5\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref5\"/>"
    "<debug-attribute name=\"adi,aux-dac-values4\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution4\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref4\"/>"
    "<debug-attribute name=\"adi,aux-dac-values3\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution3\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref3\"/>"
    "<debug-attribute name=\"adi,aux-dac-values2\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution2\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref2\"/>"
    "<debug-attribute name=\"adi,aux-dac-values1\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution1\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref1\"/>"
    "<debug-attribute name=\"adi,aux-dac-values0\"/>"
    "<debug-attribute name=\"adi,aux-dac-resolution0\"/>"
    "<debug-attribute name=\"adi,aux-dac-vref0\"/>"
    "<debug-attribute name=\"adi,aux-dac-enables\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-enable-fast-recovery-loop\"/>"
    "<debug-attribute name=\"adi,rxagc-ip3-peak-exceeded-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-ip3-over-range-thresh-index\"/>"
    "<debug-attribute name=\"adi,rxagc-ip3-over-range-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-enable-ip3-optimization-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-enable-sync-pulse-for-gain-counter\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-reset-on-rxon\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-peak-thresh-gain-control-mode\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-change-gain-if-thresh-high\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-low-thresh-prevent-gain\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-slow-loop-settling-delay\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-rx2-attack-delay\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-rx1-attack-delay\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-gain-update-counter_us\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-rx2-min-gain-index\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-rx2-max-gain-index\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-rx1-min-gain-index\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-rx1-max-gain-index\"/>"
    "<debug-attribute name=\"adi,rxagc-agc-peak-wait-time\"/>"
    "<debug-attribute name=\"adi,rxagc-power-power-log-shift\"/>"
    "<debug-attribute name=\"adi,rxagc-power-upper1-power-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-power-upper0-power-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-power-rx2-tdd-power-meas-delay\"/>"
    "<debug-attribute name=\"adi,rxagc-power-rx2-tdd-power-meas-duration\"/>"
    "<debug-attribute name=\"adi,rxagc-power-rx1-tdd-power-meas-delay\"/>"
    "<debug-attribute name=\"adi,rxagc-power-rx1-tdd-power-meas-duration\"/>"
    "<debug-attribute name=\"adi,rxagc-power-power-measurement-duration\"/>"
    "<debug-attribute name=\"adi,rxagc-power-under-range-low-power-gain-step-recovery\"/>"
    "<debug-attribute name=\"adi,rxagc-power-under-range-high-power-gain-step-recovery\"/>"
    "<debug-attribute name=\"adi,rxagc-power-under-range-low-power-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-power-under-range-high-power-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-power-power-use-bbdc2\"/>"
    "<debug-attribute name=\"adi,rxagc-power-power-use-rfir-out\"/>"
    "<debug-attribute name=\"adi,rxagc-power-power-enable-measurement\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-thresh-config\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-ovrg-sel\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-overload-power-mode\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-gain-step-attack\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-gain-step-mid-recovery\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-gain-step-low-recovery\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-gain-step-high-recovery\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-lower-thresh-peak-exceeded-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-upper-thresh-peak-exceeded-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-under-range-high-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-under-range-mid-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-under-range-low-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-high-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-overload-thresh-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-hb2-overload-duration-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-enable-hb2-overload\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-gain-step-recovery\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-gain-step-attack\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-lower-thresh-peak-exceeded-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-upper-thresh-peak-exceeded-cnt\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-low-gain-mode-low-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-low-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-low-gain-mode-high-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-apd-high-thresh\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-agc-under-range-high-interval\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-agc-under-range-mid-interval\"/>"
    "<debug-attribute name=\"adi,rxagc-peak-agc-under-range-low-interval_ns\"/>"
    "<debug-attribute name=\"adi,default-initial-calibrations-mask\"/>"
    "<debug-attribute name=\"direct_reg_access\"/>"
  "</device>"
  "<device id=\"axi-adrv9009-rx-obs-hpc\" name=\"axi-adrv9009-rx-obs-hpc\">"
    "<channel id=\"voltage0_i\" type=\"input\">"
      "<scan-element index=\"0\" format=\"le:S16/16&gt;&gt;0\"/>"
    "</channel>"
    "<channel id=\"voltage0_q\" type=\"input\">"
      "<scan-element index=\"1\" format=\"le:S16/16&gt;&gt;0\"/>"
    "</channel>"
    "<channel id=\"voltage1_i\" type=\"input\">"
      "<scan-element index=\"2\" format=\"le:S16/16&gt;&gt;0\"/>"
    "</channel>"
    "<channel id=\"voltage1_q\" type=\"input\">"
      "<scan-element index=\"3\" format=\"le:S16/16&gt;&gt;0\"/>"
    "</channel>"
    "<attribute name=\"sampling_frequency\"/>"
    "<buffer-attribute name=\"data_available\"/>"
    "<buffer-attribute name=\"length_align_bytes\"/>"
    "<buffer-attribute name=\"watermark\"/>"
    "<debug-attribute name=\"direct_reg_access\"/>"
  "</device>"
  "<device id=\"axi-adrv9009-tx-hpc\" name=\"axi-adrv9009-tx-hpc\">"
    "<channel id=\"voltage0\" type=\"output\">"
      "<scan-element index=\"0\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibphase\" filename=\"out_voltage0_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"out_voltage0_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage1\" type=\"output\">"
      "<scan-element index=\"1\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibphase\" filename=\"out_voltage1_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"out_voltage1_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage2\" type=\"output\">"
      "<scan-element index=\"2\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibphase\" filename=\"out_voltage2_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"out_voltage2_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage3\" type=\"output\">"
      "<scan-element index=\"3\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibphase\" filename=\"out_voltage3_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"out_voltage3_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"altvoltage3\" name=\"TX1_Q_F2\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage3_TX1_Q_F2_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage3_TX1_Q_F2_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage3_TX1_Q_F2_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage3_TX1_Q_F2_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage1\" name=\"TX1_I_F2\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage1_TX1_I_F2_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage1_TX1_I_F2_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage1_TX1_I_F2_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage1_TX1_I_F2_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage0\" name=\"TX1_I_F1\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage0_TX1_I_F1_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage0_TX1_I_F1_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage0_TX1_I_F1_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage0_TX1_I_F1_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage7\" name=\"TX2_Q_F2\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage7_TX2_Q_F2_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage7_TX2_Q_F2_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage7_TX2_Q_F2_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage7_TX2_Q_F2_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage6\" name=\"TX2_Q_F1\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage6_TX2_Q_F1_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage6_TX2_Q_F1_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage6_TX2_Q_F1_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage6_TX2_Q_F1_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage5\" name=\"TX2_I_F2\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage5_TX2_I_F2_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage5_TX2_I_F2_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage5_TX2_I_F2_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage5_TX2_I_F2_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage2\" name=\"TX1_Q_F1\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage2_TX1_Q_F1_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage2_TX1_Q_F1_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage2_TX1_Q_F1_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage2_TX1_Q_F1_scale\"/>"
    "</channel>"
    "<channel id=\"altvoltage4\" name=\"TX2_I_F1\" type=\"output\">"
      "<attribute name=\"frequency\" filename=\"out_altvoltage4_TX2_I_F1_frequency\"/>"
      "<attribute name=\"phase\" filename=\"out_altvoltage4_TX2_I_F1_phase\"/>"
      "<attribute name=\"raw\" filename=\"out_altvoltage4_TX2_I_F1_raw\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"out_altvoltage_sampling_frequency\"/>"
      "<attribute name=\"scale\" filename=\"out_altvoltage4_TX2_I_F1_scale\"/>"
    "</channel>"
    "<buffer-attribute name=\"data_available\"/>"
    "<buffer-attribute name=\"length_align_bytes\"/>"
    "<buffer-attribute name=\"watermark\"/>"
    "<debug-attribute name=\"pl_ddr_fifo_enable\"/>"
    "<debug-attribute name=\"direct_reg_access\"/>"
  "</device>"
  "<device id=\"axi-adrv9009-rx-hpc\" name=\"axi-adrv9009-rx-hpc\">"
    "<channel id=\"voltage0_i\" type=\"input\">"
      "<scan-element index=\"0\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibbias\" filename=\"in_voltage0_i_calibbias\"/>"
      "<attribute name=\"calibphase\" filename=\"in_voltage0_i_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"in_voltage0_i_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage0_q\" type=\"input\">"
      "<scan-element index=\"1\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibbias\" filename=\"in_voltage0_q_calibbias\"/>"
      "<attribute name=\"calibphase\" filename=\"in_voltage0_q_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"in_voltage0_q_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage1_i\" type=\"input\">"
      "<scan-element index=\"2\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibbias\" filename=\"in_voltage1_i_calibbias\"/>"
      "<attribute name=\"calibphase\" filename=\"in_voltage1_i_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"in_voltage1_i_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage_sampling_frequency\"/>"
    "</channel>"
    "<channel id=\"voltage1_q\" type=\"input\">"
      "<scan-element index=\"3\" format=\"le:S16/16&gt;&gt;0\"/>"
      "<attribute name=\"calibbias\" filename=\"in_voltage1_q_calibbias\"/>"
      "<attribute name=\"calibphase\" filename=\"in_voltage1_q_calibphase\"/>"
      "<attribute name=\"calibscale\" filename=\"in_voltage1_q_calibscale\"/>"
      "<attribute name=\"sampling_frequency\" filename=\"in_voltage_sampling_frequency\"/>"
    "</channel>"
    "<buffer-attribute name=\"data_available\"/>"
    "<buffer-attribute name=\"length_align_bytes\"/>"
    "<buffer-attribute name=\"watermark\"/>"
    "<debug-attribute name=\"pseudorandom_err_check\"/>"
    "<debug-attribute name=\"direct_reg_access\"/>"
  "</device>"
  "<device id=\"iio_sysfs_trigger\">"
    "<attribute name=\"add_trigger\"/>"
    "<attribute name=\"remove_trigger\"/>"
  "</device>"
"</context>";

ssize_t talise_tinyiiod_create(struct axi_adc *rx_adc, struct axi_dmac	*rx_dmac, struct tinyiiod **iiod);

#endif /* TALISE_TINYIIOD_H */
